### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by cesagonchu** [geekwright/gwiki#3]
gwiki/language/english/main.php

line 260

define('_MD_GWIKI_IMPORT_TEXT_FORM_DESC', 'Choose file above to import as a wiki page. No reformatting or translation will be permormed

TYPO?
permormed = performed?

**Comment by mambax7** [comment]
Yes, typo! :)

**Comment by cesagonchu** [comment]
Ok, I did a pull request:
https://github.com/geekwright/gwiki/pull/4
