### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by cesagonchu** [geekwright/gwiki#7]
Do you think I can test this version with Xoops 2.5.11 or do you have a newer version?

**Comment by mambax7** [comment]
I've made some updates on my fork, so you can test it there, but these changes are not approved by Richard, so there is a risk that they won't make it into his official version. 
But some testing is always good :) 
https://github.com/mambax7/gwiki

**Comment by cesagonchu** [comment]
You're the best!

**Comment by cesagonchu** [comment]
I don't know if this is the right place to report bugs, but I already found one.

Tested with https://github.com/mambax7/gwiki and Xoops 2.5.11 latest version.

When I check "Yes" to "Show Sample Button?" in the preferences, I get an error:

`Error: Class 'XoopsModules/Gwiki/Common/TestdataButtons' not found in file /modules/gwiki/admin/index.php line 36`

Thanks again for your help ;-)

___
My config:

Apache/2.4.18 (Ubuntu)
PHP version 7.4.9
MySQLi extension mysqlnd 7.4.9

**Comment by mambax7** [comment]
Please report issues related to my fork on the fork itself, so Richard is not bothered with bugs created by me! :) 
https://github.com/mambax7/gwiki/issues

**Comment by cesagonchu** [comment]
Done!
https://github.com/mambax7/gwiki/issues/3#issue-962869391
